version: 2.1

orbs:
 jira: circleci/jira@1.2.2
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build
      - jira/notify
      - run:
          name: Download appcenter
          command: sudo npm install appcenter-cli -g
          #cli appcenter token 7a0b040a097d4cf8b3bdd8a4f8329b5d687d2c63
      - run:
          name: Deliver to appcenter
          command: appcenter distribute release --debug --app jmatthews-rightpoint.com/LibKeystore --file demoapp/build/outputs/apk/debug/demoapp-debug.apk --group "App Testers"
          
