version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    jira: circleci/jira@1.2.2
    executor: android/android
        
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew build
      - jira/notify
